version: "3.8"

services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8000
    ports:
      - "2501:2501"
    depends_on:
      - server
